python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.4 0.01
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.5 0.01
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.6 0.01
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.7 0.01
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.3 0.05
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.4 0.05
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.5 0.05
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.2 0.1
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.3 0.1
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.4 0.1
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.2 0.15
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.3 0.15
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.4 0.15
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.2 0.2
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.3 0.2
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.4 0.2
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.2 0.1
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.3 0.1
python ~/Documents/Research/EarlyLate/EL_Working_Code/EL_parametric_sim.py 0.4 0.1

